# Generated by Django 2.1.7 on 2019-04-21 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190421_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Fee_Deatails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Add_Gym_Center_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(upload_to='Gym_center_Images')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Trainee_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainee_name', models.CharField(max_length=20)),
                ('Trainee_contact', models.IntegerField()),
                ('photo', models.ImageField(upload_to='Trainee_images/')),
                ('Experience', models.IntegerField()),
                ('Trainee_Timings', models.TimeField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Add_Gym_Center_Details')),
            ],
        ),
    ]
