# Generated by Django 2.1.7 on 2019-04-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190421_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_details',
            name='id',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
