# Generated by Django 2.1.7 on 2019-04-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190421_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_details',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
