# Generated by Django 2.1.7 on 2019-04-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190421_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration_details',
            name='email',
        ),
    ]
