# Generated by Django 2.1.7 on 2019-04-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_registration_details_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_details',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='registration_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
