# Generated by Django 2.1.7 on 2019-04-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190421_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_images')),
            ],
        ),
    ]
