# Generated by Django 2.1.7 on 2019-04-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='messsage',
            new_name='message',
        ),
    ]
