# Generated by Django 2.1.7 on 2019-04-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190421_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contact_us',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact_us',
            name='name',
        ),
        migrations.AddField(
            model_name='contact_us',
            name='Image',
            field=models.ImageField(default=1, upload_to='contactUs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_us',
            name='contact',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
